name: cafe_park
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  intl_phone_field: ^3.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  pin_code_fields: ^8.0.1
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.6.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  activity: ^1.5.3+5
  riverpod: ^2.5.1
  riverpod_generator: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
